### PR TITLE
Noarch

### PR DESCRIPTION
**Pull request by ocefpaf**

### CODE REVIEW

**Comment by kain88-de** [comment]
This causes a version resolution conflict for me. It would be nice to bump the build number.

**Comment by kain88-de** [comment]
I still get the following warning with the current blinker version on conda-forge.

```
Warning: 2 possible package resolutions (only showing differing packages):
  - conda-forge::blinker-1.4-py36_0
  - conda-forge::blinker-1.4-py_0
```

**Comment by ocefpaf** [comment]
It should be fixed now. No need to bump the build number.

**Comment by mcs07** [comment]
I have an `environment.yml` file that had `blinker=1.4=py36_0` in which has now stopped working. Changing to `blinker=1.4=py_0` fixes it, but I think it would have been better to just bump the build number.

Looks like I'm not the only one:
https://github.com/search?q=blinker%3D1.4%3Dpy36_0&type=Code&utf8=%E2%9C%93

**Pull request merged**
