### PR TITLE
MNT: Re-rendered with conda-smithy 2.1.0

### PR DESCRIPTION
**Pull request by frol**
It is to build a package for Python 3.6.

### CODE REVIEW

**Comment by frol** [comment]
All checks have passed!

**Comment by frol** [comment]
Please, merge it!

**Comment by frol** [comment]
@ocefpaf I have added myself to the maintainers and since the previous build succeeded, I think it is safe to merge it immediately.

**Comment by ocefpaf** [comment]
Thanks @frol!

**Pull request merged**
